spring.application.name=campusease-backend
server.port=8080
spring.data.mongodb.uri=mongodb://localhost:27017/campusease
spring.data.mongodb.database=campusease
jwt.secret=mySuperSecretKeyForCampusEaseApp123456789!
logging.level.org.springframework.security=DEBUG

